### ISSUE TITLE
data drifts and historical drifts - Names of statistical tests

### ISSUE THREAD

**Issue by tomaszek0** [evidentlyai/evidently#101]
Evidently provides me with the solutions I was looking for. I have one minor question, I want to add a subtitle describing the statistical test (name) to the chart. In the documentation we can find that: "To estimate the data drift, ...,    we use statistical tests to detect if the distribution has changed significantly  ...For numerical features, we use the two-sample K-S test..." but in the chapter "How to detect, evaluate and visualize historical drifts" we can read that "We use Evidently Data Drift Profile to calculate drift". Could you please explain this problem further? is it a known statistical test or an evidently specific solution?

**Comment by Liraim** [comment]
Hi @tomaszek0 ,
Thanks for your interest in out project. Here documentation about used statistical tests https://docs.evidentlyai.com/reports/data-drift#how-it-works.

**Comment by elenasamuylova** [comment]
Hi @tomaszek0 , to clarify a bit further, "Evidently Profile" refers to the JSON Profile feature when the output of the calculations is provided as a JSON summary instead of the visual dashboard. 

Both for JSON profiles and visual dashboards Evidently uses the same default statistical tests explained in the documentation @Liraim linked to. 

You can also replace the default Evidently tests using options https://docs.evidentlyai.com/step-by-step-guides/report-customization/options-for-data-target-drift#1.-choose-a-different-statistical-test-to-detect-data-drift

**Comment by tomaszek0** [comment]
Hi
Many thanks for the clarification and links.
