### ISSUE TITLE
Evaluating the classification quality of model

### ISSUE THREAD

**Issue by xsansha** [evidentlyai/evidently#14]
Mathematically, the classification quality of the model is known as Matthews Correlation Coefficient.

The metric is a true judge for the classification problems having an imbalanced set of classes.

https://en.wikipedia.org/wiki/Matthews_correlation_coefficient

**Comment by xsansha** [comment]
### Model Accuracy
![model_accuracy](https://user-images.githubusercontent.com/74548577/113571851-bee3d480-9634-11eb-9d02-3667b9c548a5.png)

### Classification quality of model
![model_classification_quality](https://user-images.githubusercontent.com/74548577/113571881-c905d300-9634-11eb-9b25-e8d97185e188.png)

If we observe the accuracy is not giving us a clear picture of the classification capability of the model.

**Comment by xsansha** [comment]
Can this feature be added?

**Comment by emeli-dral** [comment]
Hi @xsansha ,

It can indeed be useful for problems with imbalanced classes!

However, we try to minimise the number of plots for now. The goal is to provide maximum information in a single report without duplication. One of the concerns is not inflate the report in size too much (since all visualizations for now are stored in .html file). We had to vote out a few plots in a heated debate :)

The reason we excluded Matthews Correlation is that 1) it is mostly useful for imbalanced classification (especially binary), whereas we have a single report that works for all binary and multi-class alike 2) the metric itself is harder to interpret. We suggest to refer to Quality Metrics by Class to understand the variations in model performance per class.

That said, we understand some might prefer different plots for different use cases, and it is impossible to build universal "defaults". We are working on a service version of a tool where all the plots can be configured, and expect to include the full selection of options there!

**Comment by xsansha** [comment]
Thanks @emeli-dral

**Comment by emeli-dral** [comment]
Hi @xsansha ,

I just wanted to mention that now you can design custom Metrics, Widgets and Tabs. Maybe you will find convenient to customize or create your ClassificationPerformanceTab, where you can remove all irrelevant visuals and add your own ones :)
Here is the blog where we introduced the customization functionality:
https://evidentlyai.com/blog/evidently-custom-tabs-widgets-and-metrics

And here you can see how to create a custom widget with a different statistical test
https://docs.evidentlyai.com/step-by-step-guides/report-customization/add-a-custom-widget-or-tab

If you need any help with specific code or implementation, please join our Discord https://discord.com/invite/xZjKRaNp8b support channel!
