### ISSUE TITLE
Integration with Dash Plotly 

### ISSUE THREAD

**Issue by sandeeps311** [evidentlyai/evidently#191]
Hi 
Can you please let me know how to integrate with dash plotly?

**Comment by emeli-dral** [comment]
Hi @PoweredAutomation, 

I am afraid we did not plan for native integration with Dash. It is potentially possible to add it (since Evidently generates Plotly objects in the code) but that would require a lot of changes to the code. We are open for pull requests and contributions here!

Could you share what is your intended use case? Do you want to host a Dash app to connect to your model logs and acy as a monitoring dashboard?
