### ISSUE TITLE
Multiple comparisons problem

### ISSUE THREAD

**Issue by mfumanelli** [evidentlyai/evidently#238]
Hi!

I wanted to know whether you think it would be interesting to introduce some method for correcting the [multiple testing problem](https://en.wikipedia.org/wiki/Multiple_comparisons_problem), taking into account the number of tests performed for the evaluation of data drift. I realise that reporting a drift in the dataset when at least 50% of the features have a drift somewhat quells this problem, but perhaps it would be useful to have a threshold that is a function of the number of tests (e.g. Bonferroni correction to select the significance level, without using 0.05 by default).

Let me know what  do you think, in case I can try to implement it

**Comment by emeli-dral** [comment]
Hi @mfumanelli, 

Thanks for your question and willingness to contribute!

Bonferroni correction is indeed one of the possible approaches! Personally, I find it a bit tricky to interpret. Introducing a custom drift function over the results of the individual tests (or only running drift detection for the top features) gives you a bit more control. 

However, we know some users might prefer it! 

We do not plan to add Bonferroni correction as s a default option, but instead, what we are working on now is to make it easier to add custom metrics / tests / functions to the library so that users can set them as custom options. Right now there are a few statistical tests that are already implemented as options, and we are happy to see more: https://docs.evidentlyai.com/user-guide/customization/options-for-statistical-tests#available-stattest-functions

We are open for contributions! I'd only suggest to wait a couple more weeks. Soon we'll have an updated release with a change in the API, and it would be good moment to revisit the "metrics/tests library" composition.

**Comment by mfumanelli** [comment]
Perfect, thank you very much for your answer 🌈
