### ISSUE TITLE
How to interpret this graph?

### ISSUE THREAD

**Issue by ms8909** [evidentlyai/evidently#3]
<img width="1407" alt="Screenshot 2020-12-15 at 2 51 19 AM" src="https://user-images.githubusercontent.com/27916695/102140055-87cc9600-3e80-11eb-8539-759dc0ca9d29.png">

**Comment by emeli-dral** [comment]
Hi Muddassar

The plot shows the individual data points for the chosen feature from the “Production” dataset. Since we do not have a time dimension, the data is organised by index number (ID). 

The green line is the mean, as seen in the reference dataset (the baseline data you are comparing against). The green area covers one standard deviation from the mean. 

You can use this plot to explore feature behavior - e.g. visually understand when the feature started drifting, zoom in on specific data points etc.
