### ISSUE TITLE
ImportError: cannot import name 'ColumnDriftMetric' from 'evidently.metrics

### ISSUE THREAD

**Issue by ManunEbo** [evidentlyai/evidently#374]
Hi I'm testing out the evidently_metrics.ipynb, all metrics notebook.
 I've come across an issue importing anything on the following import:

from evidently.metrics import ColumnDriftMetric, DataDriftTable, DatasetDriftMetric, ColumnRegExpMetric

Any suggestions as to what the problem is?

Thanks in advance

**Comment by elenasamuylova** [comment]
Linking to a parallel Discord discussion on the same topic https://discord.com/channels/815991896916361276/815992391076806657/threads/1029052234438291458 (right now, one needs to run Evidently from source to use Metrics).

**Comment by sadashiv19** [comment]
Hi - I came across the same error. @elenasamuylova - this might be noob query - but could you please let know how to run Evidently from source ? 

Appreciate your time.

**Comment by elenasamuylova** [comment]
Hi @sadashiv19, you can follow the steps described in the Contribution Guide to run the version from the source locally.
https://github.com/evidentlyai/evidently/blob/main/CONTRIBUTING.md

In step 4, you need to make a change (since you do not need the dev version)

pip install -e .[dev] -> pip install -e .

After this, make sure to install and enable nbextension. 

jupyter nbextension install --sys-prefix --symlink --overwrite --py evidently

jupyter nbextension enable evidently --py --sys-prefix

**Comment by elenasamuylova** [comment]
You can also wait a couple of weeks, as it will be added to the package in the next release. In the meantime, you can still use the Dashboards API (described here https://docs.evidentlyai.com/features/dashboards/generate_dashboards, examples for drift here https://docs.evidentlyai.com/examples#sample-notebooks)

**Comment by elenasamuylova** [comment]
Hi @ManunEbo, just dropping a note that the Metrics have been released recently in a package https://github.com/evidentlyai/evidently/releases/tag/v0.1.59.dev0

You can work with the "All metrics" example notebook to explore  https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/evidently_metrics.ipynb

**Comment by ManunEbo** [comment]
Thanks Elena,

Perfect timing.

I'll have a look later on in the week.

Regards

Elvy
