### ISSUE TITLE
DataDrift on datasets having different dimensions 

### ISSUE THREAD

**Issue by IITGoaPyVidya** [evidentlyai/evidently#450]
Hi Community,

I am trying to find out **data drift** using **_Wasserstein distance_** on two datasets. 

My question is,
I have one dataset with only **1 sample** (_1x300 features_) and other dataset with **100 samples** (_100x300 features_) and I want to check how that one sample is drifted from 100 others? Can I put dataset with 1 sample (_1X300_) as **current dataset** and 100 sample dataset (_100x300_) as **referenced dataset**?

One more add on questions.
Is **_Wasserstein distance_** right statistical test in this case?

Any suggestions are highly appreciated !
@elenasamuylova

**Comment by elenasamuylova** [comment]
Hi @IITGoaPyVidya, it looks like you need an outlier/anomaly detection approach rather than drift detection here. I am afraid we do not have this functionality in the library yet. (Here is a blog that might be relevant https://www.evidentlyai.com/blog/ml-monitoring-drift-detection-vs-outlier-detection)

The current drift detection implementation assumes that you compare two datasets with multiple observations each. It will then compare each column (feature) in two datasets to detect per-column drift and allows you to define a dataset drift function (the share of drifting columns). 

Neither Wasserstein distance nor other statistical tests in the library are suitable for outlier detection (comparing one observation to many). Supporting outlier detection is in the list of features we are considering adding, so thanks for highlighting it might be needed!
