### ISSUE TITLE
[BUG] Broken links in the readme

### ISSUE THREAD

**Issue by OlivierBinette** [evidentlyai/evidently#489]
The following links in the READme are currently broken:

- https://docs.evidentlyai.com/reports/data-quality
- https://docs.evidentlyai.com/reports/classification-performance
- https://github.com/evidentlyai/evidently/blob/main/sample_notebooks/getting_started_tutorial.ipynb
- https://github.com/evidentlyai/evidently/blob/main/sample_notebooks/evidently_metric_presets.ipynb
- https://github.com/evidentlyai/evidently/blob/main/sample_notebooks/evidently_metrics.ipynb
- https://github.com/evidentlyai/evidently/blob/main/sample_notebooks/evidently_test_presets.ipynb
- https://github.com/evidentlyai/evidently/blob/main/sample_notebooks/evidently_tests.ipynb

Also, some links to tutorials (e.g., https://github.com/evidentlyai/evidently/tree/main/examples/integrations/mlflow_logging) point to un-rendered python notebooks rather than an HTML page in the documentation. It'd be nice to be able to see the examples without having to run them locally.

**Comment by emeli-dral** [comment]
Hi @OlivierBinette ,
thank you for letting us know! 

All links were fixed.

I agree with you that it would be much more convenient to have an HTML documentation page for each tutorial, but I'm afraid we do not have enough resources to keep a lot of doc pages up-to-date at the moment ☹️  This why we only have several tutorials in docs. 
But we regularly updated all jupyter examples, to make sure they are compatible with the package version and add new ones.  Unfortunately, most of our HTML reports cannot be rendered in python notebooks on github due to big size of the visual outputs.
