### ISSUE TITLE
No module named 'evidently.dashboard'; 'evidently' is not a package

### ISSUE THREAD

**Issue by edumagol** [evidentlyai/evidently#49]
Hi @elenasamuylova and @emeli-dral ,

Hope you guys are fine.

We were trying evidently for the first time in a Windows machine, and after installing it using command pip install evidently and trying to run it (on jupyter and also on VSCode), we got the following error:

'evidently.dashboard'; 'evidently' is not a package

See the print screen below:
![image](https://user-images.githubusercontent.com/22715100/131012715-a507a69c-48cc-498a-ba0a-920f0d606ee2.png)

We also found that the installed package, when I tried pip list was: evidently 0.1.22.dev0

Hope the above information can help you to help me.

All the best,
Edu

**Comment by emeli-dral** [comment]
Hi @edumagol ,
Looks like it happened because you have file ‘evidently.py’ at the project directory. This is why when you are trying to import ```Dashboard``` from the ```evidently.dashboard```, it refers to the  ‘evidently.py’  and says that it is not a package. 
Thus, I believe renaming of the  ‘evidently.py’  or moving it elsewhere should help.

**Comment by edumagol** [comment]
Hi @emeli-dral , sure... totally my mistake...what I shame of my self...lol...omg... how I commited such mistake... sorry for disturbing you guys with that! I should have checked that before... my apologies again. All the best girls!
