### ISSUE TITLE
Databricks ReferenceError: requirejs is not defined

### ISSUE THREAD

**Issue by kihaddadi** [evidentlyai/evidently#493]
Hi Evidently Team
I was trying to regenerate the iris dataset example on databricks:
<img width="731" alt="Screenshot 2023-01-10 at 12 33 01 PM" src="https://user-images.githubusercontent.com/104791738/211621926-afa2b05a-b35e-4293-a94d-307ef81f13c9.png">
 but I received the following error:
<img width="540" alt="Screenshot 2023-01-10 at 12 33 06 PM" src="https://user-images.githubusercontent.com/104791738/211621961-0383d77b-e0d8-4ca5-8aee-09bbf7374bb4.png">

The error is not informative and I am not able to debug it. Could you please advise me?
Thanks

**Comment by elenasamuylova** [comment]
Hi @kihaddadi , 

Could you try adding the argument to display the visual report inline?

instead of calling: 
`data_stability`

add:
`data_stability.show(mode='inline').`

The likely issue is described here: https://docs.evidentlyai.com/integrations/notebook-environments . 

Let us know if it solves the issue!

**Comment by kihaddadi** [comment]
Thanks the problem is solved.
