### ISSUE TITLE
data drifts results depends on data size

### ISSUE THREAD

**Issue by Diyago** [evidentlyai/evidently#50]
If I pass let's say 5% of the its show that there is no data drift. But with all data almost all features became drifted. I believe its because of statistic test. I suggest you to give options to choose PSI test as an option

**Comment by fyzbt** [comment]
I encounter the same pattern. The default statistical test is sensitive to sample size.

**Comment by emeli-dral** [comment]
Drift analysis is based on a statistical test so having different results due to the dataset size is entirely possible. Sample size is one of the underlying parameters that impact the test result.

The result would also vary slightly (e.g. p-values would be slightly different) when e.g. sampling is done several times.

We understand that from a practical standpoint the default tests can be “too sensitive” in case of large datasets.

We plan to address it by adding a different statistical tests (and some preprocessing logic) that will be applied if you flag the dataset as “large”. We will also add the ability to add custom metrics e.g. PSI index.

For now, I’d suggest to use sampling when analysing data drift for large datasets.

Hope that helps, and keep an eye on new releases!
