### ISSUE TITLE
Save and load reference datasets profile

### ISSUE THREAD

**Issue by marisabele** [evidentlyai/evidently#65]
Hi,
Is there possibility to save reference dateset profile and later load from file to do the data drift calculation in production environment?

**Comment by emeli-dral** [comment]
Hi @marisabele!

Technically you can save a JSON profile (the summary of metrics/statistical tests results) as a JSON file anywhere.

For example, you can save a JSON of the regression model performance report as a "performance reference". It would contain metrics such as MAE. Then, during production you can build a workflow that would compare the newly calculated production metrics against the baseline values from JSON and follow some rule-based trigger. (Right now such workflow is external to Evidently since the tool only provides the metrics). 

However, if you want to calculate data and prediction drift in production, the tool needs a complete baseline dataset (or a sample of it). Since it uses statistical tests under the hood, it won't work if only a summary of statistical properties (e.g. mean feature values, etc.) is available. In this case, it is not possible to just save some dataset "reference expectations".  

We plan to later add a feature profiling report which can be more suitable in this case. 

I hope we understood your intention right :) Otherwise please let us know a bit more about your ideal workflow!

**Comment by fferegrino** [comment]
Hi @emeli-dral, sorry to comment on this closed issue, but has this been aded to Evidently? I am trying to find documentation related to it, but can't find any.
