### ISSUE TITLE
Documentation addition: DVC integration

### ISSUE THREAD

**Issue by francesco086** [evidentlyai/evidently#819]
It would be nice to demonstrate how DVC can integrate with Evidently, similarly to [what is shown for MLFLow](https://docs.evidentlyai.com/integrations/evidently-and-mlflow).

Inspired by that, I have already added [one page on the DVC documentation](https://dvc.org/doc/user-guide/integrations/evidently), following the same example as for MLFlow.
I thought that it would be nice to show the same also on the evidently side.

I would be happy to contribute to that, if that sounds interesting to you.

**Comment by elenasamuylova** [comment]
Hi @francesco086, thanks for the willingness to contribute - we'd appreciate it!

Could you specify two things when making the contribution:
- That this is an example that shows how to use Evidently Reports with [DVCLive](https://dvc.org/doc/dvclive) - and name it **Evidently and DVCLive**. Since there are other ways to integrate the two tools (for example, with DVC pipelines like shown [here](https://www.youtube.com/watch?v=qFnwZ653Aks), this might be a bit confusing otherwise.
- Could you add a note that it is a community-contributed integration like in [this ](example)?

Thank you!

**Comment by francesco086** [comment]
Hi @elenasamuylova !

I did what you asked and a little more, added the notebook in the examples folder 🤗

You can preview the result here: https://francesco.gitbook.io/docs.evidentlyai.com/

**Comment by francesco086** [comment]
By the way, if it is not asking for too much, I would appreciate if you could add the [hacktoberfest](https://hacktoberfest.com/) tag to this issue, as I am participating. I see that you are also involved in this already...

**Comment by elenasamuylova** [comment]
Hi @francesco086 - thanks for the contribution, we will take a look soon!

I added the `hacktoberfest` tag to the issue just in case. However, I believe it should work even without it - the requirement is to have a “hacktoberfest” topic on the project level (which Evidently does).
